Numpy is not already installed in python while os is


    pip install numpy
Then to update
    
        python.exe -m pip install --upgrade pip

In [247]:
! pip install numpy     
# to install latest version


[notice] A new release of pip is available: 24.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [248]:
#To simply install
# pip install numpy ------> terminal hi run hogi yh,jupyter m directly nhi kr skte

# After installing stored in c drive (global environment)
# but hm sari libraries ko to download nhi krenge kyunki wrna hmara c drive fill ho jayega
# so we install them in virtual environment to save space
# python -m venv folder_name

In [249]:
# To create virtual environment
# python -m venv folder_name

# To activate 
# .\datascience\Scripts\activate

# To deactivate 
# deactivate -----> simply 

#then from above, select kernel you have made

# For every virtual environment we have to install its personalized jupyter

In [250]:
print("Hello kese ho")

Hello kese ho


#### ** like in big projects hme bhut sari libraries ki need hoti h to hr ko manually install krne ki jgh hm ek requirements.txt file bna lete h jisme hm library and uska version likh dete h**

#### Then in terminal

    pip install -r .\requirements.txt

In [251]:
import numpy as np
np.__version__

'2.4.6'

# Numpy
NumPy is a powerful Python library used for:

1. Fast numerical computations
2. Working with arrays and matrices
3. Mathematical functions
4. Scientific computing and data analysis

**The name stands for Numerical Python.**

| Topic                     | Description                                                  | Example                   |
| ------------------------- | ------------------------------------------------------------ | ------------------------- |
| **NumPy**                 | A Python library used for numerical and scientific computing | `import numpy as np`      |
| **Purpose**               | Used for fast array operations and mathematical calculations | Data analysis, ML         |
| **Main Feature**          | Provides powerful multidimensional arrays                    | `np.array()` --> to create array             |
| **Installation**          | Install using pip                                            | `pip install numpy`       |
| **Import Statement**      | Import NumPy with alias `np`                                 | `import numpy as np`      |
| **Array Creation**        | Create NumPy arrays                                          | `np.array([1,2,3])`       |
| **Zeros Function**        | Creates array filled with 0                                  | `np.zeros((2,2))`         |
| **Ones Function**         | Creates array filled with 1                                  | `np.ones((2,2))`          |
| **Arange Function**       | Creates array in a range                                     | `np.arange(0,10,2)`       |
| **Random Values**         | Generates random numbers                                     | `np.random.rand(3)`       |
| **Shape**                 | Returns dimensions of array                                  | `arr.shape`               |
| **Reshape**               | Changes array dimensions                                     | `arr.reshape(2,3)`        |
| **Indexing**              | Access specific element                                      | `arr[0]`                  |
| **Slicing**               | Access multiple elements                                     | `arr[1:4]`                |
| **Addition**              | Element-wise addition                                        | `a + b`                   |
| **Multiplication**        | Element-wise multiplication                                  | `a * b`                   |
| **Mean**                  | Finds average value                                          | `np.mean(arr)`            |
| **Sum**                   | Finds total sum                                              | `np.sum(arr)`             |
| **Maximum Value**         | Finds largest element                                        | `np.max(arr)`             |
| **Minimum Value**         | Finds smallest element                                       | `np.min(arr)`             |
| **Standard Deviation**    | Measures spread of data                                      | `np.std(arr)`             |
| **2D Array (Matrix)**     | Array with rows and columns                                  | `np.array([[1,2],[3,4]])` |
| **Advantages of NumPy**   | Faster and more memory efficient than Python lists           | Useful in large datasets  |
| **Applications**          | Used in AI, ML, Data Science, Image Processing               | Neural networks           |
| **Libraries Using NumPy** | Base library for many ML/data tools                          | Pandas, TensorFlow        |


| Type of Array              | Description                             | Example                                   |
| -------------------------- | --------------------------------------- | ----------------------------------------- |
| **1D Array**               | Contains only one row of elements       | `np.array([1,2,3,4])`                     |
| **2D Array**               | Contains rows and columns (matrix form) | `np.array([[1,2],[3,4]])`                 |
| **3D Array**               | Collection of 2D arrays                 | `np.array([[[1,2],[3,4]],[[5,6],[7,8]]])` |
| **Multidimensional Array** | Array with more than 3 dimensions       | `np.array([[[[1]]]])`                     |


In [252]:
# Firstly we will create a list and then convert it in array

In [253]:
lst = list(range(1,20))

In [254]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [255]:
type(lst)

list

In [256]:
# Array is homogenous while list is heterogenous
# Array is 10 times faster than list

# To create array we use np.array()
arr = np.array(lst)

In [257]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [258]:
lst = [1,2,3,4,5]
arr = np.array(lst)

In [259]:
arr


array([1, 2, 3, 4, 5])

In [260]:
type(arr)

numpy.ndarray

In [261]:
arr = np.array([12,34,5,6,7,9])
arr

array([12, 34,  5,  6,  7,  9])

In [262]:
arr = np.array(range(1,20))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [263]:
type(arr)

numpy.ndarray

In [264]:
arr = np.arange(1,10)  #To create array in a range numpy provides "arange function"
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [265]:
type(arr)

numpy.ndarray

In [266]:
arr = np.zeros(10)   # To initialize array with zero
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [267]:
arr = np.zeros(0)
arr  

array([], dtype=float64)

In [268]:
arr = np.ones(10)   # To initialize array with ones
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### To create 2D array

    np.array((rows,columns))

    Total number of elements = rows * column

In [269]:
arr = np.zeros((5,10))    
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [270]:
print(arr.ndim)   # To get dimension of array

2


In [271]:
arr = np.linspace(1,10,5)   # 5 random elements between 1 to 10 
print(arr)
print(type(arr))

[ 1.    3.25  5.5   7.75 10.  ]
<class 'numpy.ndarray'>


In [272]:
arr = np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [273]:
# To change shape of array use array_name.reshape
arr = arr.reshape(10,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [274]:
arr = arr.reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [275]:
np.random.randint(1,5,10)  #To create random elements np.random.randint(start,end,size)

array([2, 2, 1, 1, 4, 1, 1, 1, 2, 1], dtype=int32)

In [276]:
# # ## 3D array
# # arr = arr.reshape(3,5,2)
# # arr

# array([[[ 0,  1],
#         [ 2,  3],
#         [ 4,  5],
#         [ 6,  7],
#         [ 8,  9]],

#        [[10, 11],
#         [12, 13],
#         [14, 15],
#         [16, 17],
#         [18, 19]],

#        [[20, 21],
#         [22, 23],
#         [24, 25],
#         [26, 27],
#         [28, 29]]])

In [277]:
arr = np.random.randint(1,5,(5,6))
arr

array([[2, 2, 4, 1, 3, 1],
       [4, 1, 4, 2, 1, 1],
       [4, 3, 3, 2, 1, 3],
       [4, 4, 1, 4, 2, 2],
       [4, 3, 2, 2, 2, 1]], dtype=int32)

In [278]:
arr = np.random.random(10)   #gives random from 0 to 1
arr

array([0.47862514, 0.16858719, 0.51479772, 0.69812553, 0.4468904 ,
       0.89275329, 0.79173266, 0.43206881, 0.96653053, 0.86090411])

In [279]:
arr = np.random.random((10,3))   #gives random from 0 to 1
arr

array([[0.5428325 , 0.82250823, 0.36141795],
       [0.07317003, 0.93053663, 0.17674824],
       [0.32738816, 0.61511843, 0.95777761],
       [0.61508708, 0.42842616, 0.69699831],
       [0.50273104, 0.69473967, 0.48287028],
       [0.65959609, 0.55202002, 0.63160945],
       [0.90374165, 0.05611583, 0.06031944],
       [0.95111786, 0.41782978, 0.83690594],
       [0.3713906 , 0.16815835, 0.67277121],
       [0.0232546 , 0.17643502, 0.29514536]])

In [280]:
arr = np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [345]:
print("Shape of array:",arr.shape)
print("No. of dim:",arr.ndim)
print("Size of array:",arr.size)
print("Datatype of items in array:",arr.dtype)

Shape of array: (5, 15, 3)
No. of dim: 3
Size of array: 225
Datatype of items in array: int64


In [282]:
lst = [[1,2,3],[4,5,6]]     # 2D list
lst

[[1, 2, 3], [4, 5, 6]]

In [283]:
arr = np.array(lst)   # We can directly convert our 2D list in 2D array
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [284]:
arr = np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [285]:
arr.shape

(12, 5)

In [286]:
arr.T   #array_name.T -----> to transpose array 

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [287]:
arr.transpose   #Or we can directly use array_name.transpose 
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [288]:
# Indexing and slicing
arr[0,0]    #first 0---> row second 0 column

np.int64(0)

In [289]:
arr[-1,-1]

np.int64(59)

In [290]:
arr[2:4]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [291]:
arr[2:4,3:5]

array([[13, 14],
       [18, 19]])

In [292]:
arr[2:4,3:]

array([[13, 14],
       [18, 19]])

In [293]:
arr[9:11,1:3]

array([[46, 47],
       [51, 52]])

In [294]:
arr[5:7,2:4]

array([[27, 28],
       [32, 33]])

In [295]:
arr[0:9,3:4]

array([[ 3],
       [ 8],
       [13],
       [18],
       [23],
       [28],
       [33],
       [38],
       [43]])

In [296]:
arr[0:9,3]

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43])

In [297]:
arr[-1,-1]=100   #We can change array index value
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58, 100]])

## 3D Array

In [ ]:
arr = np.arange(225).reshape(5,15,3) #(5---> no. of table , 15 ----> no. of row in each table , 3 -----> no. of column in each table)
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

### Indexing of 3D Array

In [307]:
arr[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [308]:
arr[0][0]

array([0, 1, 2])

In [309]:
arr[0,0]

array([0, 1, 2])

In [310]:
arr[0][0][0]

np.int64(0)

In [311]:
arr[-1]

array([[180, 181, 182],
       [183, 184, 185],
       [186, 187, 188],
       [189, 190, 191],
       [192, 193, 194],
       [195, 196, 197],
       [198, 199, 200],
       [201, 202, 203],
       [204, 205, 206],
       [207, 208, 209],
       [210, 211, 212],
       [213, 214, 215],
       [216, 217, 218],
       [219, 220, 221],
       [222, 223, 224]])

In [312]:
arr[4]

array([[180, 181, 182],
       [183, 184, 185],
       [186, 187, 188],
       [189, 190, 191],
       [192, 193, 194],
       [195, 196, 197],
       [198, 199, 200],
       [201, 202, 203],
       [204, 205, 206],
       [207, 208, 209],
       [210, 211, 212],
       [213, 214, 215],
       [216, 217, 218],
       [219, 220, 221],
       [222, 223, 224]])

In [316]:
arr[4][14]

array([222, 223, 224])

In [317]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

### Slicing

In [318]:
arr[0:5,0]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [319]:
arr[0:5,0,0]

array([  0,  45,  90, 135, 180])

In [320]:
arr[0:5,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [328]:
arr[0:5,:1]

array([[[  0,   1,   2]],

       [[ 45,  46,  47]],

       [[ 90,  91,  92]],

       [[135, 136, 137]],

       [[180, 181, 182]]])

In [329]:
arr[0:5,:,1:2]

array([[[  1],
        [  4],
        [  7],
        [ 10],
        [ 13],
        [ 16],
        [ 19],
        [ 22],
        [ 25],
        [ 28],
        [ 31],
        [ 34],
        [ 37],
        [ 40],
        [ 43]],

       [[ 46],
        [ 49],
        [ 52],
        [ 55],
        [ 58],
        [ 61],
        [ 64],
        [ 67],
        [ 70],
        [ 73],
        [ 76],
        [ 79],
        [ 82],
        [ 85],
        [ 88]],

       [[ 91],
        [ 94],
        [ 97],
        [100],
        [103],
        [106],
        [109],
        [112],
        [115],
        [118],
        [121],
        [124],
        [127],
        [130],
        [133]],

       [[136],
        [139],
        [142],
        [145],
        [148],
        [151],
        [154],
        [157],
        [160],
        [163],
        [166],
        [169],
        [172],
        [175],
        [178]],

       [[181],
        [184],
        [187],
        [190],
        [193],
        [196],
  

In [ ]:
arr[0:5]

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [337]:
arr[2,3:5,1:3]

array([[100, 101],
       [103, 104]])

In [339]:
arr[4,-1,-1]

np.int64(224)

In [340]:
arr[-1,-1,-1]

np.int64(224)

In [341]:
arr[4,14,2]

np.int64(224)

In [342]:
arr[-1,-1,2]

np.int64(224)

In [343]:
arr[4,14,-1]

np.int64(224)

In [344]:
arr[4,-1,2]

np.int64(224)

In [348]:
arr[0:5,-1:,2:]

array([[[ 44]],

       [[ 89]],

       [[134]],

       [[179]],

       [[224]]])

In [346]:
print("Shape of array:",arr.shape)
print("No. of dim:",arr.ndim)
print("Size of array:",arr.size)
print("Datatype of items in array:",arr.dtype)

Shape of array: (5, 15, 3)
No. of dim: 3
Size of array: 225
Datatype of items in array: int64


In [351]:
arr[4,-1,1] = 1000

In [352]:
arr

array([[[   0,    1,    2],
        [   3,    4,    5],
        [   6,    7,    8],
        [   9,   10,   11],
        [  12,   13,   14],
        [  15,   16,   17],
        [  18,   19,   20],
        [  21,   22,   23],
        [  24,   25,   26],
        [  27,   28,   29],
        [  30,   31,   32],
        [  33,   34,   35],
        [  36,   37,   38],
        [  39,   40,   41],
        [  42,   43,   44]],

       [[  45,   46,   47],
        [  48,   49,   50],
        [  51,   52,   53],
        [  54,   55,   56],
        [  57,   58,   59],
        [  60,   61,   62],
        [  63,   64,   65],
        [  66,   67,   68],
        [  69,   70,   71],
        [  72,   73,   74],
        [  75,   76,   77],
        [  78,   79,   80],
        [  81,   82,   83],
        [  84,   85,   86],
        [  87,   88,   89]],

       [[  90,   91,   92],
        [  93,   94,   95],
        [  96,   97,   98],
        [  99,  100,  101],
        [ 102,  103,  104],
        [ 105,  

In [357]:


arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 6, 8])

print("Array 1 :", arr1)
print("Array 2 :", arr2)


# Multiplication
print("\nMultiplication (*)")
print("arr1 * arr2 =", arr1 * arr2)

# Division
print("\n Division (/)")
print("arr1 / arr2 =", arr1 / arr2)

# Addition
print("\n Addition (+)")
print("arr1 + arr2 =", arr1 + arr2)

# Subtraction
print("\n Subtraction (-)")
print("arr1 - arr2 =", arr1 - arr2)

# Positive Sign with Multiplication
print("\nMultiplication with Unary Plus (* +)")
print("arr1 * +arr2 =", arr1 * +arr2)

# Floor Division
print("\n Floor Division (//)")
print("arr1 // +arr2 =", arr1 // +arr2)

print("\nAll operations completed successfully!")

Array 1 : [10 20 30 40]
Array 2 : [2 4 6 8]

Multiplication (*)
arr1 * arr2 = [ 20  80 180 320]

 Division (/)
arr1 / arr2 = [5. 5. 5. 5.]

 Addition (+)
arr1 + arr2 = [12 24 36 48]

 Subtraction (-)
arr1 - arr2 = [ 8 16 24 32]

Multiplication with Unary Plus (* +)
arr1 * +arr2 = [ 20  80 180 320]

 Floor Division (//)
arr1 // +arr2 = [5 5 5 5]

All operations completed successfully!


In [355]:
arr1.sort()

In [356]:
arr1

array([10, 20, 30, 40])

In [358]:
arr=np.array([12,4,56,78,2,1,19,58])

In [359]:
arr.sort()

In [362]:
print(arr.sort())    #it does not return anything

None


In [363]:
arr

array([ 1,  2,  4, 12, 19, 56, 58, 78])

In [365]:
arr=np.arange(225)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [368]:
arr.reshape(15,3,5)

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14]],

       [[ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29]],

       [[ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44]],

       [[ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59]],

       [[ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89]],

       [[ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104]],

       [[105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119]],

       [[120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134]],

       [[135, 136, 137, 138, 139],
  

In [ ]:
# NumPy completed